### ISSUE TITLE
debug release 1.0.9 - Fixed Cmd_Post return value

### ISSUE THREAD

**Issue by Brazzabro** [SmileYzn/AccuracyFix#13]
there are problems with the server crash
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0xf090ecb0 in CAccuracyFix::TraceLine(float const*, float const*, int, edict_s*, TraceResult*) () from /serverfiles/cstrike/addons/accuracyfix/dlls/accuracyfix_mm.so
[Current thread is 1 (Thread 0xf7c54900 (LWP 2072676))]
#0  0xf090ecb0 in CAccuracyFix::TraceLine(float const*, float const*, int, edict_s*, TraceResult*) () from /serverfiles/cstrike/addons/accuracyfix/dlls/accuracyfix_mm.so
#1  0xffa6cd20 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
No symbol table info available.
```

**Comment by SmileYzn** [comment]
Post versions of ReHLDS, ReGameDLL_CS, linux system etc.

**Comment by Brazzabro** [comment]
ReHLDS 
```
ReHLDS version: 3.13.0.0-dev
Build date: 13:41:42 Jan 09 2024 (3559)
```
ReGameDLL 
```
ReGameDLL version: 5.26.0.668-dev
Build date: 19:02:48 Dec 31 2023
```
linux system
```
Ubuntu 20.04.6 LTS
Linux 5.4.0-169-generic #187-Ubuntu SMP Thu Nov 23 14:52:28 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by SmileYzn** [comment]
Try with ReGameDLL_CS 5.26.0.690-dev

Ps. Maybe with this ReHLDS to:
https://github.com/dreamstalker/rehlds/actions/runs/7964786615
